### ISSUE TITLE
 this.WorkerClass is not a constructor

### ISSUE THREAD

**Issue by stelasido** [Vibrant-Colors/node-vibrant#85]
Hi, I am getting this error with the example from the docs:

> in promise) TypeError: this.WorkerClass is not a constructor.

This is my code:

`        console.log(src);
        Vibrant.from(src).getPalette()
            .then((palette) => console.log(palette))`

I am using `React`.

**Comment by akfish** [comment]
Sorry for the confusion. We are still finalizing the documentations.

You will need webpack and worker-loader for this to work. 
Relevant docs are in the develop branch:
https://github.com/akfish/node-vibrant/tree/develop#webpack-configuration

**Comment by KyzaGitHub** [comment]
I am getting this error with a Vuejs/Nuxtjs server while trying to run this client side. I'm not quite understanding what I need to do to fix this. What I am trying to do is get the color palette from an image on the web page. This image is random every time the page loads, which is why I need to run this client side.

**Comment by crutchcorn** [comment]
I'll do my best to take a look at how we can ship down a built version of this that doesn't require webpack. Timeline is hesitant, as I have some family health problems, so please be patient :)

**Comment by MadReal** [comment]
Same problem, using vue.js though

**Comment by markmakes** [comment]
Same problem, using Angular 7 :)

**Comment by AggressivelyMeows** [comment]
Same problem with Vue.js
Using Webpack

**Comment by YourCreepyNeighbor** [comment]
@AggressivelyMeows, make sure you have **worker-loader** installed and change webpack configuration. In case of using Vue, you need to edit **vue.config.js**.

```
//vue.config.js
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.worker\.js$/,
          use: { loader: "worker-loader" }
        }
      ]
    }
  },
}
```

**Comment by nkCreation** [comment]
Hi. Can't find a may to make it work. I have the loader in my webpack config but still have the error...

**Comment by nkCreation** [comment]
@akfish any ideas ?

**Comment by crutchcorn** [comment]
Please avoid tagging maintainers directly - FWIW I'm one the current maintainer of the project.

Is there any way someone could provide a minimal reproduction that I can take a look into? I'm not able to reproduce

**Comment by ivgtr** [comment]
Currently, [npmjs](https://www.npmjs.com/package/node-vibrant) has an alpha version distributed as a latest version.
In my case(use Nuxt.js), I downgraded from "3.2.1-alpha.1" to "3.1.6", and the error was solved.

**Comment by micahlt** [comment]
@ivgtr Your solution worked perfectly to resolve this issue!

```bash
npm remove node-vibrant && npm install node-vibrant@3.1.6
```

**Comment by vova42matters** [comment]
@ivgtr solved! thanks!
added config [from docs](https://github.com/Vibrant-Colors/node-vibrant/tree/develop#webpack-configuration) and downgraded to `node-vibrant@3.1.6`
Hope this issue will be solved in next versions of `node-vibrant`
Using React and ejected react-create-app

**Comment by c0ncentus** [comment]
please not make like https://github.com/storybookjs/storybook/issues , as you see there is more issue for webpack crap config than "true" issue of the main functionnality. 

Make usage easiest possible please.

**Comment by ramfattah** [comment]
> @ivgtr Your solution worked perfectly to resolve this issue!
> 
> ```shell
> npm remove node-vibrant && npm install node-vibrant@3.1.6
> ```

thank you!!!!!

**Comment by zanjie1999** [comment]
Same problem, using Vue.js 3 with Vite

**Comment by bitdom8** [comment]
Thanks @ivgtr

**Comment by bitdom8** [comment]
The error is resolved however when I build sveltekit it appears 

```
vendor-fab8aa60.js:30 Uncaught (in promise) TypeError: this.WorkerClass is not a constructor
    at e._findIdleWorker (vendor-fab8aa60.js:30)
    at e._tryDequeue (vendor-fab8aa60.js:30)
    at e._enqueue (vendor-fab8aa60.js:30)
    at e.invoke (vendor-fab8aa60.js:30)
    at e.invokeWorker (vendor-fab8aa60.js:30)
    at e.process (vendor-fab8aa60.js:30)
    at e._process (vendor-fab8aa60.js:30)
    at vendor-fab8aa60.js:30
```

**Comment by micahlt** [comment]
> The error is resolved however when I build sveltekit it appears
> 
> Uncaught TypeError: Cannot read property 'filters' of undefined``

Unless that error is directly connected to this issue (which I don't believe it is), you'll need to create a separate issue for that.

**Comment by beeftony** [comment]
Still having the same problem with Vue3, Nuxt3, node-vibrant@3.1.6 and worker-loader@3.0.8...

**Comment by Lucienest** [comment]
It's been two years, you guys still couldn't fix it??

**Comment by crutchcorn** [comment]
@Lucienest you're welcome to open a PR to fix this.

**Comment by twofingerrightclick** [comment]
This is rough. Hoping someone tackles this. Its definitely very high percentage of sites where images are hosted independent of app these days.

**Comment by chiarapaskulin** [comment]
```
SelfServiceDemo.tsx:50 Error: TypeError: this.WorkerClass is not a constructor
    at WorkerPool2._findIdleWorker (pool.ts:35:16)
    at WorkerPool2._tryDequeue (pool.ts:72:23)
    at WorkerPool2._enqueue (pool.ts:60:10)
    at WorkerPool2.invoke (pool.ts:110:17)
    at WorkerManager2.invokeWorker (index.ts:25:30)
    at WorkerPipeline2.process (client.ts:22:26)
    at Vibrant2._process (index.ts:49:30)
    at index.ts:70:27
    at async handleLaunch (SelfServiceDemo.tsx:46:29)

```

Downgrading didn't work for me.

**Comment by saeho** [comment]
How would one use this package/get around this issue if webpack is not possible? (ie. Deno runtime)

**Comment by crutchcorn** [comment]
Can you test this against v4 and let me know if this issue is resolved?

**Comment by crutchcorn** [comment]
This should be fully resolved as of v4. Closing and suggesting people migrate to one of those versions
